services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"  # חיבור ל-MQTT ב-PORT 1883
    environment:
      MOSQUITTO_ALLOW_ANONYMOUS: "true"  # אפשרות חיבור אנונימי (אם דרוש)
    volumes:
      - mosquitto-data:/mosquitto/data  # שמירת נתונים לקונטיינר Mosquitto

volumes:
  mosquitto-data:

#  mongodb:
#    image: mongo:latest
#    ports:
#      - "27017:27017"
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
#
#  db-sql:
#    image: postgres:13
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: 1234
#      POSTGRES_DB: suspicious_messages
#    volumes:
#      - db_data:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#
#volumes:
#  db_data: