version: '3'
services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    ports:
      - "7077:7077"  
      - "8080:8080"  
    environment:
      - SPARK_MODE=master
    networks:
      - spark-net

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    depends_on:
      - spark-master
    ports:
      - "8081:8081"  
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077  
    networks:
      - spark-net

networks:
  spark-net:
    driver: bridge
